"""change name content to tag_content or todo_content

Revision ID: 4056deeb9991
Revises: e897e0f75cb9
Create Date: 2017-11-01 23:12:26.426000

"""

# revision identifiers, used by Alembic.
revision = '4056deeb9991'
down_revision = 'e897e0f75cb9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('tag_content', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_tag_tag_content'), 'tag', ['tag_content'], unique=True)
    op.drop_index('ix_tag_tagname', table_name='tag')
    op.drop_column('tag', 'tagname')
    op.add_column('todo', sa.Column('todo_content', sa.String(length=64), nullable=True))
    op.drop_column('todo', 'content')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('content', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('todo', 'todo_content')
    op.add_column('tag', sa.Column('tagname', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('ix_tag_tagname', 'tag', ['tagname'], unique=True)
    op.drop_index(op.f('ix_tag_tag_content'), table_name='tag')
    op.drop_column('tag', 'tag_content')
    ### end Alembic commands ###
