"""add_tag

Revision ID: e897e0f75cb9
Revises: 0cf21a5344c6
Create Date: 2017-11-01 16:23:33.954000

"""

# revision identifiers, used by Alembic.
revision = 'e897e0f75cb9'
down_revision = '0cf21a5344c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tagname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_tagname'), 'tag', ['tagname'], unique=True)
    op.add_column(u'todo', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'tag', ['tag_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column(u'todo', 'tag_id')
    op.drop_index(op.f('ix_tag_tagname'), table_name='tag')
    op.drop_table('tag')
    ### end Alembic commands ###
